# Site settings
title: One Byte at a Time
email: khaptonstall93@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Kyle, a junior Computer Science major, available for hire! 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  khaptonstall

# Build settings
markdown: kramdown
