# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "Kyle Haptonstall"
description: > # this means to ignore newlines until "email:"
   Journey of a Computer Science Major in Small Town, Illinois

email: khaptonstall93@gmail.com
#blog logo
logo: "/assets/images/kh-logo.jpg"
# blog cover
cover: "/assets/images/cover.jpg"

name: 'Kyle Haptonstall'
author: 'Kyle Haptonstall'
author_image: "/assets/images/author.jpg"

paginate:	5

exclude: ["GithubBlog.json", "privatekey.p12"]

url: "http://khaptonstall.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	linkedin
    url:	https://www.linkedin.com/pub/kyle-haptonstall/67/839/a55
    desc: Connect with me on LinkedIn
    share_url: 
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/khaptonstall
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
    
analytics :
  provider : google
  google : 
      tracking_id : 'UA-63016211-1'

jekyll_ga:
  service_account_email: 929771368653-q1tmanog0tf5oib4kb2g0jojgoovlgii@developer.gserviceaccount.com   # service account email address
  key_file: privatekey.p12  # service account private key file
  key_secret: notasecret    # service account private key's password
  profileID: ga:102373413        # profile ID 
  start: last month         # Beginning of report
  end: now                  # End of report
  metric: ga:pageviews      # Metric code
  segment:                  # optional
  filters:                  # optional
  sort: true                # Sort posts by this metric
  
  
  